export const projectData = {
    "UI/UX": [
        {
            id: 1,
            title: "KBMDSI 2025",
            description: "External website design for student organization in Faculty of Computer Science Brawijaya University (Instagram : @kbmdsi_ub)",
            image: "/kbmdsi.png",
            isFeatured: true,
            video: "/kbmdsi_video.mp4",
            team: ["Afiif Al Hauzaan (me), Sabitha Marsyarira N, Shananda Putri A."],
            tags: ["UI/UX", "Figma"]
        },
        {
            id: 2,
            title: "RAJA Brawijaya 2025",
            description: "Designed a high-fidelity digital dashboard for the university's largest annual orientation, serving 16,000+ active users. Optimized information architecture to handle peak-hour traffic for attendance and assignment management with zero learning curve.",
            image: "/rajabrawijaya.png",
            team: ["Afiif Al Hauzaan (me)", "UI/UX Team"],
            website: "https://rajabrawijaya.ub.ac.id/",
            tags: ["UI/UX", "Design System", "Figma"]
        },
        {
            id: 3,
            title: "Greventure",
            description: "A map-based social media platform designed to reconnect people with their surroundings. It helps users discover local places and activities, especially those related to urban sustainability. Greventure encourages young people to bring their cities to life digitally while fostering connections with the environment and promoting efforts to care for it",
            video: "/greventure.mp4",
            team: ["Afiif Al Hauzaan (me)", "Putra Cakrawala A", "Elgin Brian W.", "Nugraha Billy V."],
            figma: "https://www.figma.com/proto/ww5UapdbwQnvEVFzYDkgUC/Ada-hackjam-coy?page-id=28%3A277&node-id=88-5212&p=f&viewport=-1517%2C-568%2C0.14&t=cLRxyw3YDLlOFzkW-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=88%3A5203&show-proto-sidebar=1",
            tags: ["SDGs 11", "UI/UX"]
        },
        {
            id: 4,
            title: "EcoWardrobe",
            description: "An app for tackling fast fashion waste by enabling users to sell, buy, and donate pre-loved clothes, while promoting sustainable fashion through innovative features like a camera scanning tool to personalize shopping experiences",
            image: "/ecoward.png",
            isFeatured: true,
            width: "500",
            team: ["Achmad Firdaus A.", "Afiif Al Hauzaan (me)", "Taufani Soviana Z."],
            figma: "https://www.figma.com/proto/45cnPOFNzEJimDPg5cOMfY/The-Ace-Undip---Semoga-Ga-NT?page-id=1%3A2&node-id=486-1301&p=f&viewport=321%2C175%2C0.06&t=MmtC3HoBqNWuuBxq-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=486%3A1289&show-proto-sidebar=1",
            tags: ["SDGs 12", "UI/UX"]
        },
        {
            id: 5,
            title: "Mentorify",
            description: "Mentorify is a mobile-based application that provides essential information about tutors and additional resources in the education field. With Mentorify, users can find tutors that match their specific needs and learning styles, making the learning process more effective and enjoyable. The app also offers features that make it easier to search for and access details about tutor schedules and experience, helping users select the best match for their educational goals.",
            image: "/mentorify.png",
            team: ["Afiif Al Hauzaan (me)", "Aditya Rizki P."],
            figma: "https://www.figma.com/proto/ArGcCKH35t6GndJnMZvmrc/kelompok-les-lesgooooooooo?page-id=0%3A1&node-id=21-64&p=f&viewport=20%2C264%2C0.05&t=phPHRzuSl9ksaj7Q-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=21%3A64&show-proto-sidebar=1",
            tags: ["SDGs 4", "UI/UX"]
        },
        {
            id: 6,
            title: "EchoSleep",
            description: "An app designed to enhance your sleep quality by providing real-time sleep monitoring, personalized tips, and insightful statistics. EchoSleep helps track your sleep patterns, identifies disturbances, and offers tailored recommendations for a more restful night. Whether you're dealing with sleep apnea or simply struggling to get better rest, the app connects you with sleep specialists for consultations. With EchoSleep, you can take control of your sleep health, improve your overall well-being, and wake up refreshed every day.",
            image: "/echosl.png", // Image source for the project
            team: ["Alexander Imanuel W.", "M. Ridwan Novriansyah", "Afiif Al Hauzaan (me)"],
            figma: "https://www.figma.com/proto/TXwj2drey3LphUHEepd4L4/EchoSleep?page-id=25%3A3822&node-id=150-11929&p=f&viewport=62%2C-5670%2C0.24&t=PT4MrPsii8SRYYKy-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=150%3A11970&show-proto-sidebar=1",
            tags: ["SDGs 3", "UI/UX"]
        },
        {
            id: 7,
            title: "PetCare",
            description: "An app designed to help pet owners, particularly those with dogs and cats, manage the health and well-being of their pets. It provides comprehensive solutions, including information on pet care and online consultations with veterinarians at affordable prices. Users can share experiences and receive support, fostering a community that cares for animal health. With PetCare, pet owners can easily maintain the health of their pets while ensuring their safety, addressing issues such as rabies, infections, parasites, and metabolic disorders.",
            image: "/petcare.png",
            team: ["Ayudia Jayanti", "Afiif Al Hauzaan (me)", "Adisty Ningrum D."],
            figma: "https://www.figma.com/proto/mpqfDaaHlyY9r00eHOREhO/PetCare?page-id=5%3A92&node-id=174-2311&p=f&viewport=356%2C230%2C0.09&t=dhdw33BseK85QWNN-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=174%3A2311&show-proto-sidebar=1",
            tags: ["SDGs 3", "UI/UX"]
        },
    ],
    "Graphic Design": [
        {
            id: 8,
            title: "HOLOGY 7.0",
            description: "One of my works in HOLOGY 7.0 is this competition poster. It's the biggest technology event in Brawijaya University hosting seminar and competition.",
            image: "/hologi.png",
            isFeatured: true,
            tags: ["Technology", "Poster", "Designs"],
            design: "https://www.instagram.com/hology_ub/",
        },
        {
            id: 9,
            title: "Rantau Ngalam Kuy",
            description: "A campus expo & roadshow for introducing Brawijaya University in Pontianak, West Kalimantan (my city)",
            image: "/rnk.png",
            isFeatured: true,
            tags: ["Campus Expo", "Designs"],
            design: "https://drive.google.com/file/d/1yUk1gG_Ja1So-F_OKPiWMrEzg3TK1olz/view?usp=sharing",
        },
        {
            id: 10,
            title: "Mobile JKN",
            description: "Submission for 4C Competition FILKOM UB. Mobile JKN is an real app by Ministry of Health Indonesia to fasilitate health administrations. The infographic describes its functions and encouraging people to use it.",
            image: "/4c.png",
            team: ["Aurora Nisa K.", "Najwa Afifah", "Elvira Rosa K.", "Afiif Al Hauzaan (me)"],
            tags: ["Infographic", "Health", "Designs"],
            design: "https://drive.google.com/file/d/1-Dj43PT3H7w_5q7XXQAoJBFU-J-o3pyE/view?usp=sharing",
        },
        {
            id: 11,
            title: "MPLS",
            description: "MPLS (Masa Pengenalan Lingkungan Sekolah) is a welcoming event in my previous high school SMAN 1 Pontianak. I personally really like this design",
            image: "/mpls.png",
            tags: ["Poster", "Designs"],
            design: "https://drive.google.com/file/d/1Zid2_M2jeKkTozU171wFdoniTk31yPup/view?usp=sharing",
        },
    ],
    "Websites": [
        {
            id: 12,
            title: "Kak Sarah",
            description: "AI-powered Socratic tutoring platform utilizing React (Inertia.js) and Laravel. Tested with 35+ concurrent students in a live classroom setting with zero errors, rate-limits, or server constraints.",
            image: "/kaksarah.png",
            isFeatured: true,
            team: ["Afiif Al Hauzaan (me)", "Arif Ammar S.", "Naila Rahma N.", "Achmad Hasbil W.", "Ghefira Addien M.", "Shananda Putri A."],
            tags: ["React", "Laravel", "Inertia.js", "OpenAI"],
            github: "https://github.com/afifalhauzan/kelassarah_web"
        },
        {
            id: 13,
            title: "SMKN 5 Malang",
            description: "Fullstack school assessment and gallery platform serving 1,000+ users. Implemented Next.js 14 (App Router) and Laravel, utilizing SWR for optimized client-side data fetching and caching.",
            image: "/smkn5.png",
            isFeatured: true,
            team: ["Afiif Al Hauzaan (me)"],
            tags: ["Next.js 14", "Laravel", "SWR", "Docker"],
            github: "https://github.com/afifalhauzan/galerismkn5_web"
        },
        {
            id: 14,
            title: "IT FEST 2025",
            description: "National-scale competition platform that handled 15,000+ views. Successfully sliced the design and integrated a Next.js frontend with a Golang-based backend API using a feature-based architecture and GitHub PR workflow.",
            image: "/itfest.png",
            isFeatured: true,
            team: ["Muhammad Syauqi I.", "Alfi Tsani", "Ketut Bagus Wedanta A. M.", "Afiif Al Hauzaan (me)", "Azmi Al Ghifari Rahman", "Achmad Hasbil W."],
            tags: ["Next.js", "Golang API", "Tailwind CSS"],
            website: "https://itfest-filkom.com/"
        },
        {
            id: 15,
            title: "AsistenKita",
            description: "Domestic worker marketplace built with Next.js and TypeScript. Implements TanStack Query for efficient server state management including caching, pagination, and filtering.",
            image: "/asistenkita.png",
            isFeatured: true,
            team: ["Afiif Al Hauzaan (me)", "Atha Azzahra K. N.", "Elvira Rosa K."],
            tags: ["Next.js 14", "TypeScript", "TanStack Query", "Appwrite Backend"],
            website: "https://asistenkita.vercel.app/"
        },
        {
            id: 16,
            title: "Xhiexplore",
            description: "A virtual art exhibition by Scienta SMANSA (Class of 2020-2023, SMA Negeri 1 Pontianak) showcasing over 40 creative works. Hosted using Spatial",
            image: "/xhiexplore.png",
            isFeatured: true,
            team: ["Afiif Al Hauzaan (me)", "Wira Kasyfurrahman."],
            tags: ["3D Museum", "Bootstrap", "Unity"],
            website: "https://afifalhauzan.github.io/xhiexplore-site/",
        },
        {
            id: 17,
            title: "Past Portfolio",
            description: "My first portfolio website, showcasing many types of projects.",
            image: "/framer.png",
            tags: ["Framer", "Website"],
            website: "https://afifalhauzan.framer.website/",
        },
        {
            id: 18,
            title: "PortalMABA",
            description: "A backend-focused website for welcoming and managing freshman students. The feature includes attendance, activity notebook, managing groups, and assignment",
            image: "/portalmaba.png",
            tags: ["Lavavel", "MySQL", "Tailwind", "Laravel Breeze"],
            github: "https://github.com/afifalhauzan/pkkmb_admin_pweb",
        },
        {
            id: 19,
            title: "Simple Blog Site",
            description: "A Technology Blog website for learning Laravel + Blade + Tailwind.",
            team: ["Afiif Al Hauzaan (me)", "Yusuf Whisnu T. W.", "Zahwa Naurah P."],
            image: "/blog.png",
            tags: ["Lavavel", "MySQL", "Tailwind"],
            github: "https://github.com/afifalhauzan/Blog-Beginner-group-7",
        },
    ],
    "Videography": [
        {
            id: 20,
            title: "Eftychia",
            isFeatured: true,
            description: "Class of 2023 SMAN 1 Pontianak's Farewell. It's a 6 minute aftermovie that showcases our graduation party, took 1 month for editing this.",
            image: "/efty.png",
            tags: ["School", "Aftermovie"],
            videoLink: "https://www.instagram.com/p/C81OsVYsLfu/",
        },
        {
            id: 21,
            title: "HOLOGY 7.0 Trailer",
            isFeatured: true,
            description: "A promotion for HOLOGY 7.0. Showcases many visual effects created in After Effects.",
            image: "/holt.png",
            tags: ["Technology", "Visual Effects"],
            videoLink: "https://www.instagram.com/reel/C99lsqzyDS-/",
        },
        {
            id: 22,
            title: "Makrab PTI 23",
            description: "Captures the solidarity of PTI'23 FILKOM UB.",
            image: "/makrab.png",
            tags: ["Aftermovie"],
            videoLink: "https://www.instagram.com/reel/C58SGYlSDS-/",
        },
        {
            id: 23,
            title: "Schotival",
            description: "An Aftermovie for a scholarship event in FILKOM UB. Themed around superhero, we add many motion graphics and animations",
            image: "/scho.png",
            team: ["Mukti Abdi", "Afiif Al Hauzaan (me)", "Ahmad Zaidan"],
            tags: ["Motion Graphics", "Aftermovie"],
            videoLink: "https://www.instagram.com/reel/DECg9FSyb8w/",
        },
        {
            id: 24,
            title: "Pusoko",
            description: "A 17-minute short film about culture of Indonesia. It's a big project involving 35 of the Scienta class. As an video editor and VFX editor.",
            image: "/pusoko.png",
            tags: ["Short Film", "Theatre", "Visual Effects"],
            videoLink: "https://www.instagram.com/p/CSs6HZ_h7Yu/",
        },
        {
            id: 25,
            title: "Synergy of Symphony",
            description: "The usual Aftermovie around an event in FILKOM UB.",
            image: "/sos.png",
            tags: ["Aftermovie"],
            videoLink: "https://www.instagram.com/p/DDd9cPLprQi/",
        },
        {
            id: 26,
            title: "Sebelah Mata",
            description: "Short film about honesty themed around highschool. Got into national finalists from KPK",
            image: "/sebelahm.png",
            tags: ["Short Film"],
            videoLink: "https://youtu.be/8ZS_ld4OwLY?si=IIym9qrw3XhNa7pD",
        },
    ],
    "Motion Graphics": [
        {
            id: 27,
            title: "Eftychia",
            isFeatured: true,
            description: "Class of 2023 SMAN 1 Pontianak's Farewell. It's a 6 minute aftermovie that showcases our graduation party, took 1 month for editing this.",
            image: "/efty.png",
            tags: ["School", "Aftermovie"],
            videoLink: "https://www.instagram.com/p/C81OsVYsLfu/",
        },
    ]
};